apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  generation: 31
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-als-portal-db
  name: db
  namespace: als-portal
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-als-portal-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        workload.user.cattle.io/workloadselector: deployment-als-portal-db
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: splash
        - name: TZ
          value: US/Pacific
        envFrom:
        - secretRef:
            name: dbinit
            optional: false
        image: mongo:4.2
        imagePullPolicy: Always
        name: db
        ports:
        - containerPort: 27017
          name: directaccess
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - NET_BIND_SERVICE
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data/db
          name: potaldb
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: potaldb
        persistentVolumeClaim:
          claimName: potaldb

