apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "43"
    field.cattle.io/creatorId: u-k6z3wvz5on
    field.cattle.io/publicEndpoints: "null"
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"30","field.cattle.io/creatorId":"u-k6z3wvz5on","field.cattle.io/publicEndpoints":"null","nersc.gov/gid":"79966","nersc.gov/gids":"55452,71384,76870,79966,73814,91806,92619,93859,94656","nersc.gov/uid":"79966","nersc.gov/username":"dmcreyno"},"creationTimestamp":"2021-03-11T01:57:02Z","generation":74,"labels":{"cattle.io/creator":"norman","workload.user.cattle.io/workloadselector":"deployment-als-portal-splash-ingest-poller"},"name":"splash-ingest-poller","namespace":"als-portal","resourceVersion":"145941859","selfLink":"/apis/apps/v1/namespaces/als-portal/deployments/splash-ingest-poller","uid":"183e11cb-d15f-47b3-96ab-423ba6384fa8"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"workload.user.cattle.io/workloadselector":"deployment-als-portal-splash-ingest-poller"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"cattle.io/timestamp":"2021-05-06T18:37:29Z"},"creationTimestamp":null,"labels":{"workload.user.cattle.io/workloadselector":"deployment-als-portal-splash-ingest-poller"}},"spec":{"containers":[{"env":[{"name":"APP_MODULE","value":"splash_ingest_manager.api:app"},{"name":"PORT","value":"8080"},{"name":"SCICAT_BASEURL","value":"http://app:3000/api/v3"},{"name":"SPLASH_LOG_LEVEL","value":"DEBUG"},{"name":"THUMBS_ROOT","value":"/data_mover/thumbs"},{"name":"DATABROKER_DB_NAME","valueFrom":{"secretKeyRef":{"key":"DATABROKER_DB_NAME","name":"db-connection","optional":false}}},{"name":"DATABROKER_DB_URI","valueFrom":{"secretKeyRef":{"key":"DATABROKER_DB_URI","name":"db-connection","optional":false}}},{"name":"INGEST_DB_NAME","valueFrom":{"secretKeyRef":{"key":"INGEST_DB_NAME","name":"db-connection","optional":false}}},{"name":"INGEST_DB_URI","valueFrom":{"secretKeyRef":{"key":"INGEST_DB_URI","name":"db-connection","optional":false}}}],"image":"registry.nersc.gov/als/splash_ingest_poller:v0.2.1","imagePullPolicy":"Always","name":"splash-ingest-poller","resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"add":["NET_BIND_SERVICE"],"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":79966},"stdin":true,"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","tty":true,"volumeMounts":[{"mountPath":"/data_mover","name":"data-mover"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"registry-nersc"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":55452},"terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/global/cfs/cdirs/als/data_mover","type":"Directory"},"name":"data-mover"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-05-05T22:06:15Z","lastUpdateTime":"2021-05-05T22:06:15Z","message":"Deployment
      has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2021-03-11T01:57:02Z","lastUpdateTime":"2021-05-06T18:37:33Z","message":"ReplicaSet
      \"splash-ingest-poller-7fb947d754\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":74,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}'
    nersc.gov/collab_uids: 71383,57074,92620
    nersc.gov/gid: "79966"
    nersc.gov/gids: 55452,76870,79966,91806,93859,94656,94721,96414,99273,100403
    nersc.gov/roles: user
    nersc.gov/uid: "79966"
    nersc.gov/username: dmcreyno
  creationTimestamp: "2021-05-06T23:27:31Z"
  generation: 79
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-als-portal-splash-ingest-poller
  name: splash-ingest-poller
  namespace: als-portal
  resourceVersion: "513086227"
  selfLink: /apis/apps/v1/namespaces/als-portal/deployments/splash-ingest-poller
  uid: 99827720-8c03-48f2-94ba-3be34eeace4d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-als-portal-splash-ingest-poller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2023-03-21T14:54:22Z"
        nersc.gov/collab_uids: 71383,57074,92620
        nersc.gov/gid: "79966"
        nersc.gov/gids: 55452,76870,79966,91806,93859,94656,94721,96414,99273,100403
        nersc.gov/roles: user
        nersc.gov/uid: "79966"
        nersc.gov/username: dmcreyno
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-als-portal-splash-ingest-poller
    spec:
      containers:
      - env:
        - name: APP_MODULE
          value: splash_ingest_manager.api:app
        - name: INGEST_LOG_LEVEL
          value: DEBUG
        - name: PORT
          value: "8080"
        - name: SCICAT_BASEURL
          value: http://app:3000/api/v3/
        - name: SPLASH_LOG_LEVEL
          value: DEBUG
        - name: THUMBS_ROOT
          value: /data_mover/thumbs
        - name: DATABROKER_DB_NAME
          valueFrom:
            secretKeyRef:
              key: DATABROKER_DB_NAME
              name: db-connection
        - name: DATABROKER_DB_URI
          valueFrom:
            secretKeyRef:
              key: DATABROKER_DB_URI
              name: db-connection
        - name: INGEST_DB_NAME
          valueFrom:
            secretKeyRef:
              key: INGEST_DB_NAME
              name: db-connection
        - name: INGEST_DB_URI
          valueFrom:
            secretKeyRef:
              key: INGEST_DB_URI
              name: db-connection
        - name: SCICAT_INGEST_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: scicat-ingestor
        - name: SCICAT_INGEST_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: scicat-ingestor
        image: ghcr.io/als-computing/splash-ingest-poller:master
        imagePullPolicy: Always
        name: splash-ingest-poller
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 79966
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data_mover
          name: data-mover
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 55452
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /global/cfs/cdirs/als/data_mover
          type: Directory
        name: data-mover
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-15T21:40:53Z"
    lastUpdateTime: "2023-03-21T14:55:05Z"
    message: ReplicaSet "splash-ingest-poller-648bd68447" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-07-27T16:29:30Z"
    lastUpdateTime: "2023-07-27T16:29:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 79
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
